[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ofxstatement-wise"
version = "0.0.0"
description = "Wise plugin for ofxstatement"
readme = "README.md"
license = {text = "GPL-3.0-or-later"}
keywords = ["ofx", "banking", "statement", "wise"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Natural Language :: English",
    "Topic :: Office/Business :: Financial :: Accounting",
    "Topic :: Utilities",
    "Environment :: Console",
    "Operating System :: OS Independent",
]
dependencies = [
    "ofxstatement @ git+https://github.com/wigny/ofxstatement",
]
requires-python = ">=3.9"

[project.urls]
Homepage = "https://github.com/wigny/ofxstatement-wise"

[project.entry-points.ofxstatement]
wise = "ofxstatement_wise.wise:WisePlugin"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[tool.mypy]

[tool.pycodestyle]
max-line-length = 88

[tool.black]
line-length = 88
target-version = ['py39']

[dependency-groups]
dev = [
    "mypy",
    "pytest",
    "black",
    "syrupy",
]
